In [37]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [38]:
price_df = pd.read_csv("HousePricePrediction.csv")

In [42]:
price_df.head()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [43]:
price_df.describe()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice
count,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2918.000000,2918.000000,1460.000000
mean,1459.000000,57.137718,10168.114080,5.564577,1971.312778,1984.264474,49.582248,1051.777587,180921.195890
std,842.787043,42.517628,7886.996359,1.113131,30.291442,20.894344,169.205611,440.766258,79442.502883
min,0.000000,20.000000,1300.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,34900.000000
25%,729.500000,20.000000,7478.000000,5.000000,1953.500000,1965.000000,0.000000,793.000000,129975.000000
50%,1459.000000,50.000000,9453.000000,5.000000,1973.000000,1993.000000,0.000000,989.500000,163000.000000
75%,2188.500000,70.000000,11570.000000,6.000000,2001.000000,2004.000000,0.000000,1302.000000,214000.000000
max,2918.000000,190.000000,215245.000000,9.000000,2010.000000,2010.000000,1526.000000,6110.000000,755000.000000

In [44]:
price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [46]:
#handeling missing sales price values
price_mean = price_df['SalePrice'].mean()
price_df['SalePrice'] = price_df['SalePrice'].fillna(price_mean)

In [47]:
#removing the rows with empty/null cells
price_df.dropna()

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.00000
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.00000
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.00000
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.00000
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.00000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,2914,160,RM,1936,Inside,Twnhs,7,1970,1970,CemntBd,0.0,546.0,180921.19589
2915,2915,160,RM,1894,Inside,TwnhsE,5,1970,1970,CemntBd,0.0,546.0,180921.19589
2916,2916,20,RL,20000,Inside,1Fam,7,1960,1996,VinylSd,0.0,1224.0,180921.19589
2917,2917,85,RL,10441,Inside,1Fam,5,1992,1992,HdBoard,0.0,912.0,180921.19589
2918,2918,60,RL,9627,Inside,1Fam,5,1993,1994,HdBoard,0.0,996.0,180921.19589

In [48]:
price_df.drop(['Id'], axis = 1, inplace = True)

In [49]:
#one-hot encoding
price_df = pd.get_dummies(price_df, columns = ["MSZoning", "LotConfig", "BldgType", "Exterior1st"], drop_first = True, dtype = int)

In [51]:
#train test split
X = price_df.drop(['SalePrice'], axis=1)
Y = price_df['SalePrice']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state = 42)

In [53]:
price_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   MSSubClass           2919 non-null   int64
 1   LotArea              2919 non-null   int64
 2   OverallCond          2919 non-null   int64
 3   YearBuilt            2919 non-null   int64
 4   YearRemodAdd         2919 non-null   int64
 5   BsmtFinSF2           2918 non-null   float64
 6   TotalBsmtSF          2918 non-null   float64
 7   SalePrice            2919 non-null   float64
 8   MSZoning_FV          2919 non-null   int64
 9   MSZoning_RH          2919 non-null   int64
 10  MSZoning_RL          2919 non-null   int64
 11  MSZoning_RM          2919 non-null   int64
 12  LotConfig_CulDSac    2919 non-null   int64
 13  LotConfig_FR2        2919 non-null   int64
 14  LotConfig_FR3        2919 non-null   int64
 15  LotConfig_Inside     2919 non-null   int64
 16  BldgType_2fmCon      2919 non-null   int64
 17  BldgType_Duplex      2919 non-null   int64
 18  BldgType_Twnhs       2919 non-null   int64
 19  BldgType_TwnhsE      2919 non-null   int64
 20  Exterior1st_AsphShn  2919 non-null   int64
 21  Exterior1st_BrkComm  2919 non-null   int64
 22  Exterior1st_BrkFace  2919 non-null   int64
 23  Exterior1st_CBlock   2919 non-null   int64
 24  Exterior1st_CemntBd  2919 non-null   int64
 25  Exterior1st_HdBoard  2919 non-null   int64
 26  Exterior1st_ImStucc  2919 non-null   int64
 27  Exterior1st_MetalSd  2919 non-null   int64
 28  Exterior1st_Plywood  2919 non-null   int64
 29  Exterior1st_Stone    2919 non-null   int64
 30  Exterior1st_Stucco   2919 non-null   int64
 31  Exterior1st_VinylSd  2919 non-null   int64
 32  Exterior1st_Wd Sdng  2919 non-null   int64
 33  Exterior1st_WdShing  2919 non-null   int64
dtypes: float64(3), int64(31)
memory usage: 775.5 KB

In [57]:
price_df.isnull().sum()

MSSubClass             0
LotArea                0
OverallCond            0
YearBuilt              0
YearRemodAdd           0
BsmtFinSF2             1
TotalBsmtSF            1
SalePrice              0
MSZoning_FV            0
MSZoning_RH            0
MSZoning_RL            0
MSZoning_RM            0
LotConfig_CulDSac      0
LotConfig_FR2          0
LotConfig_FR3          0
LotConfig_Inside       0
BldgType_2fmCon        0
BldgType_Duplex        0
BldgType_Twnhs         0
BldgType_TwnhsE        0
Exterior1st_AsphShn    0
Exterior1st_BrkComm    0
Exterior1st_BrkFace    0
Exterior1st_CBlock     0
Exterior1st_CemntBd    0
Exterior1st_HdBoard    0
Exterior1st_ImStucc    0
Exterior1st_MetalSd    0
Exterior1st_Plywood    0
Exterior1st_Stone      0
Exterior1st_Stucco     0
Exterior1st_VinylSd    0
Exterior1st_Wd Sdng    0
Exterior1st_WdShing    0
dtype: int64

In [62]:
price_df = price_df.dropna(axis = 0)

In [63]:
price_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2918 entries, 0 to 2918
Data columns (total 34 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   MSSubClass           2918 non-null   int64
 1   LotArea              2918 non-null   int64
 2   OverallCond          2918 non-null   int64
 3   YearBuilt            2918 non-null   int64
 4   YearRemodAdd         2918 non-null   int64
 5   BsmtFinSF2           2918 non-null   float64
 6   TotalBsmtSF          2918 non-null   float64
 7   SalePrice            2918 non-null   float64
 8   MSZoning_FV          2918 non-null   int64
 9   MSZoning_RH          2918 non-null   int64
 10  MSZoning_RL          2918 non-null   int64
 11  MSZoning_RM          2918 non-null   int64
 12  LotConfig_CulDSac    2918 non-null   int64
 13  LotConfig_FR2        2918 non-null   int64
 14  LotConfig_FR3        2918 non-null   int64
 15  LotConfig_Inside     2918 non-null   int64
 16  BldgType_2fmCon      2918 non-null   int64
 17  BldgType_Duplex      2918 non-null   int64
 18  BldgType_Twnhs       2918 non-null   int64
 19  BldgType_TwnhsE      2918 non-null   int64
 20  Exterior1st_AsphShn  2918 non-null   int64
 21  Exterior1st_BrkComm  2918 non-null   int64
 22  Exterior1st_BrkFace  2918 non-null   int64
 23  Exterior1st_CBlock   2918 non-null   int64
 24  Exterior1st_CemntBd  2918 non-null   int64
 25  Exterior1st_HdBoard  2918 non-null   int64
 26  Exterior1st_ImStucc  2918 non-null   int64
 27  Exterior1st_MetalSd  2918 non-null   int64
 28  Exterior1st_Plywood  2918 non-null   int64
 29  Exterior1st_Stone    2918 non-null   int64
 30  Exterior1st_Stucco   2918 non-null   int64
 31  Exterior1st_VinylSd  2918 non-null   int64
 32  Exterior1st_Wd Sdng  2918 non-null   int64
 33  Exterior1st_WdShing  2918 non-null   int64
dtypes: float64(3), int64(31)
memory usage: 797.9 KB

In [67]:
X = price_df.drop(['SalePrice'], axis=1)
Y = price_df['SalePrice']

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state = 42)

model = LinearRegression()
model.fit(X_train, Y_train)

LinearRegression()

In [68]:
Y_predict = model.predict(X_test)

In [69]:
from sklearn.metrics import r2_score
r2 = r2_score(Y_test, Y_predict)
print(r2)

0.3091193863879014

In [71]:
#standardization
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [73]:
model = LinearRegression()
model.fit(X_train_scaled, Y_train)

y_predict = model.predict(X_test_scaled)
r2 = r2_score(Y_test, Y_predict)
print(r2)

0.3091193863879259